companieshouse/restricted-word-web

src/clients/axiosInstance.ts

Just made it so httpsAgent is undefined if there is no proxy config from env vars

Added option for no proxy tunnel for other environments

---

Makefile

Added test-unit to makefile

---

views/includes/filters.html

Fixed filter

---

views/all.html

Added ID for UI testing to be easier

Added word id to word rows

---

views/add-new-word.html
views/all.html
views/delete-word.html
views/includes/filters.html

Added ids to buttons

---

src/controllers/RestrictedWordController.ts
src/routers/RestrictedWordRouter.ts
test/clients/RestrictedWordApiClient.test.ts
test/controllers/RestrictedWordController.test.ts

Changing action names to getAction/postAction etc

Updated action names

---

views/add-new-word.html
views/all.html
views/delete-word.html
views/includes/filters.html

Did some general changes to table headers, buttons etc

IVP-915: Completed requested changes

---

views/all.html

New word notifcation has the new word capitalised and a full stop added.

IVP-940: Capitalised word that has just been added

---

package-lock.json
src/clients/RestrictedWordApiClient.ts
src/controllers/RestrictedWordController.ts
src/middleware/authenticationMiddleware.ts
test/clients/RestrictedWordApiClient.test.ts
test/controllers/RestrictedWordController.test.ts

Added unit tests as they were forgotten

IVP-962: Unit tested restricted word web

---

src/clients/RestrictedWordApiClient.ts
src/clients/RestrictedWordViewModel.ts
test/clients/RestrictedWordApiClient.test.ts

Stripping out @domain from emails. Checking deleted for undefined as it is optional

IVP-987: Stripped @domain from emails, updated unit tests

---

views/all.html

Combine date and user columns for created and deleted by

IVP-988-combined date and user columns

---

views/add-new-word.html

Updated message for IVP-986 to the specified message

IVP-986: Updated the message when a new word contains conflicts

---

views/add-new-word.html

Just removed "new" from button text

IVP-986: Removed new from button text

---

package.json

IVP-986: Added session version

---

src/app.ts

Change for rebuild

---

views/all.html
views/delete-word.html
views/word.html

Add delete button to the new word page and removing from the list. Fixing the back button to go back to the page instead of the list.

Added delete modified views

---

views/all.html

Just adding a column to show super restricted status

IVP-1255: Added super restricted column to table

---

views/word.html

This is to fix the word missing from the page title

IVP-1387: Fixed title

---

src/clients/RestrictedWordApiClient.ts
test/controllers/RestrictedWordController.test.ts

Fixed unit test and added some more to it

Fixed unit tests and added to

---

src/controllers/RestrictedWordController.ts

Fixed the paging missing the super restricted

Fixed paging missing the super restricted

---

test/controllers/RestrictedWordController.test.ts

Fixed two failing unit tests which didn't get updated when another thing was fixed.

IVP-1261: Fixed failing tests

---

Makefile
package.json
sonar-project.properties

IVP-1497: Added sonar files

---

package-lock.json
package.json

Fixed security vulnerabilities in restricted word web

---

gulpfile.js
package-lock.json
package.json

Try to fix parent1 build by reverting dependency changes.

Revert dependency changes

---

package-lock.json
package.json

Change node sass version to 4.14.1

change node sass version

---

README.md

Remove whitespace from readme

---

package-lock.json
package.json
start.sh

[](url)
I have checked the Meson Marathon on parent1 and cidev and the version of `account.ch.gov.uk` exceeds the required `4.8.88`.

Fix for Closed Browser Session Time Out

---

test/controllers/healthcheckController.test.ts

https://companieshouse.atlassian.net/browse/CC-682
Adding unit test for healthcheck endpoint

CC-682 Add heathcheck unit test

---

terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
terraform/groups/ecs-service/variables.tf

JIRA: https://companieshouse.atlassian.net/browse/CC-695
Added cidev terraform profile values.

cc 695 tf profile cidev

---

Makefile
src/controllers/RestrictedWordController.ts

https://companieshouse.atlassian.net/browse/CC-682
Pipeline needs a 'make lint' target so adding that and fixing couple of lint issues

CC-682 Add lint to makefile and fix lint issues

---

test/middleware/createAuthenticationMiddleware.test.ts

https://companieshouse.atlassian.net/browse/CC-682
Improve test coverage on auth middleware by adding test for the healthcheck endpoint condition

CC-682 Improve auth middleware test coverage

---

Makefile

https://companieshouse.atlassian.net/browse/CC-682
Adding security-check to makefile to fix pipeline

CC-682 Adding make security-check target

---

terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
terraform/groups/ecs-service/variables.tf

Adding restricted_word_web_port and chs_url into cidev config

Fix vars for cidev

---

terraform/groups/ecs-service/locals.tf

change healthcheck matcher to 302 as healthcheck is asking for a log in.

Change healthcheck matcher to 302

---

terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars

PR: https://companieshouse.atlassian.net/browse/CC-709
Staging config.

cc-709 Add terrafrom staging config

---

Dockerfile
Tiltfile.dev
package.json
src/app.ts
src/clients/RestrictedWordApiClient.ts
src/clients/RestrictedWordDto.ts
src/clients/RestrictedWordViewModel.ts
src/controllers/RestrictedWordController.ts
test/clients/RestrictedWordApiClient.test.ts
test/controllers/RestrictedWordController.test.ts
views/delete-word.html

PR: https://companieshouse.atlassian.net/browse/PAS-417
Implement delete justification into restricted-word-web and fix unit tests.

Feature/pas 417/delete justification

---

package-lock.json
src/app.ts
src/clients/RestrictedWordApiClient.ts
src/controllers/RestrictedWordController.ts
src/error/RestrictedWordError.ts
test/clients/RestrictedWordApiClient.test.ts
test/controllers/RestrictedWordController.test.ts
views/add-new-word.html

https://companieshouse.atlassian.net/browse/PAS-450
When the user wants to add a new word, they now have to enter a reason.

PAS-450 Add text input for created reason

---

package-lock.json

Fix security issue in @babel/traverse package
Auto fix using 
```npm audit fix```
Issue: https://github.com/advisories/GHSA-67hx-6x53-jw92

Fix @babel/traverse security issue

---

views/word.html

Fixed delete word view without reason.

Fixed delete word view without reason

---

src/controllers/RestrictedWordController.ts
test/controllers/RestrictedWordController.test.ts
views/delete-word.html

Ticket: https://companieshouse.atlassian.net/browse/PAS-417
Change wording of delete reason

Change wording of delete reason

---

src/clients/RestrictedWordApiClient.ts
src/clients/RestrictedWordDto.ts
src/clients/RestrictedWordViewModel.ts
src/controllers/RestrictedWordController.ts
test/clients/RestrictedWordApiClient.test.ts
test/controllers/RestrictedWordController.test.ts
views/add-new-word.html

Jira ticket: https://companieshouse.atlassian.net/browse/PAS-435
Added the ability to choose a category when creating a new word and updated unit tests

add category selection to create a new word

---

README.md

Resolves [PAS-451](https://companieshouse.atlassian.net/browse/PAS-451)
Update content to README regarding the categories/justification from ECCT updates. 
[PAS-451]: https://companieshouse.atlassian.net/browse/PAS-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update README to support categories changes

---

package-lock.json
package.json
src/app.ts
views/add-new-word.html
views/delete-word.html
views/includes/filters.html
views/layout.html
views/word.html

* Adds the CSRF Mitigation Middleware and adds CSRF tokens into requests to protect against CSRF attacks

Implement CSRF mitigations

---

package-lock.json
package.json

Resolves: [BI-13682](https://companieshouse.atlassian.net/browse/BI-13682)
[BI-13682]: https://companieshouse.atlassian.net/browse/BI-13682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix dependencies for session not found error

---

src/app.ts
src/middleware/createCsrfErrorMiddleware.ts

Fix for "uncaughtException: Cannot find module 'middleware/createCsrfErrorMiddleware
Resolves: SEC-116

Fix for "uncaughtException: Cannot find module 

---

package-lock.json
package.json

Fix for security vulnerabilities
Resolves: ASM-355

Fix for security vulnerabilities

---

package-lock.json
package.json
src/middleware/createCsrfErrorMiddleware.ts
test/middleware/createCsrfErrorMiddleware.test.ts

Fix security vulnerabilities and lint errors. Added status code dependency to fix magic number error.
Resolves: SEC-137

Fix security vulnerabilities and lint errors

---

README.md

Add information for creating test users (roles required) via a link to confluence

Add extra info on test user - referring back to confluence
